
[[authors]]
name = "Andrey Voynov"
photo = "andrey.jpg"
corresponding = false
institution = "Bauman Moscow State Technical University (BMSTU), Russia"
credit = ["software", "validation", "writing-review-editing"]
bio = "Andrey Voynov is a master's student in software engineering with a strong passion for programming and free/open-source software. He began coding in QBasic and Pascal during school, actively competed in Informatics Olympiads, and earned a 2nd-degree diploma at the 2020 All-Russian Forum of Scientific Youth. Andrey has created hundreds of projects, contributed to many others, and since discovering Typst in 2023, uses it exclusively for documents and slides, promoting its adoption in Russia through teaching, curriculum updates, and feature contributions."

[[authors]]
name = "Alberto Corbi"
photo = "alberto.jpg"
corresponding = true
email = "alberto.corbi@unir.net"
institution = "Universidad Internacional de La Rioja (UNIR), Av. de la Paz, 137, 26006 Logroño, La Rioja, Spain"
credit = ["software", "conceptualization", "writing-original-draft", "project-administration", "supervision"]
bio = "Alberto Corbi is a tenured professor at the Universidad Internacional de La Rioja (UNIR). He is currently involved in a variety of research fields: e-learning standards, systems interoperability, medical physics, radiological protection, STEAM education, the social implications of technology (with emphasis on social networks), e-health advancement. He has published over 20 research papers on all these subjects, and he is a speaker and knowledge disseminator on radios, podcasts, scientific workshops, magazines, academic settings, and outreach events."




[[authors]]
name = "Pau López-Oliver"
photo = "pau.jpg"
corresponding = false
email = "pau.oliver@uv.es"
institution = "The University of Valencia (UV), Carrer del Dr. Moliner, 50, Burjassot, Valencia, Spain"
credit = ["software", "writing-review-editing"]
bio = "Pau is a theoretical physicist with a M.Sc. in Advanced Physics from the University of Valencia and a B.Sc. in Physics from the University of Murcia. His research centers on understanding particle creation in quantum field theory in curved and dynamical backgrounds. He is dedicated to advancing fundamental physics while promoting science communication. He currently teaches in the Physics degree program at the Universidad Internacional de La Rioja (UNIR)."

[[authors]]
name = "David Gil"
photo = "david.jpg"
corresponding = false
email = "dgilo@aemet.es"
institution = "Agencia Estatal de Meteorología (AEMET), Leonardo Prieto Castro, 8, Madrid, España"
credit = ["software", "methodology", "formal-analysis"]
bio = "David Gil works at the Spanish weather service (AEMET) as an IT Specialist. He is currently pursuing a Bachelor's degree in Physics at the Universidad Internacional de La Rioja (UNIR) with the goal of becoming a meteorologist and working with Numerical Weather Prediction systems. His work involves programming (preferring functional programming languages), high-performance computing, and developing web applications that deliver weather forecast products to forecasters. He is also engaged in projects related to containerization technologies and workflow automation, aiming to bridge computer science and meteorology."

[paper]
title = "Typst: a modern typesetting engine for science"
abstract = "Typst is a modern, markup-based typesetting system designed for creating professional documents with a focus on simplicity and performance. Combining a clean syntax with powerful scripting capabilities, it allows users to write structured content while automating layout and styling. Unlike LaTeX, with its steep learning curve and verbose syntax, Typst offers a more intuitive approach. It compiles documents incrementally, enabling faster rendering compared to traditional engines. Typst also integrates built-in version control and collaborative features, addressing gaps in other typesetting systems' workflows. Compared to alternatives, Typst is lighter and more approachable, though LaTeX remains dominant in academia due to its extensive package ecosystem. Alternatives like Markdown (with Pandoc) are simpler but lack Typst's fine-grained control over layout. Microsoft Word and other WYSIWYG tools are easy to use but lack reproducibility and automation. Typst strikes a balance, blending Markdown's readability with TeX's precision, and adds modern features such as real-time collaboration. Its growing library of templates and packages positions it as a compelling alternative for technical writing, academic papers, and beyond."
keywords = ["Typesetting system", "Incremental parsers", "Markup language", "Paper composition", "Reproducibility", "Performance"]
doi = "10.9781/ijimai.XXXX.02.006"
received-date = 2024-07-08
accepted-date = 2024-12-18
published-date = 2025-02-10
publication-year = 2025
volume = 0
number = 0
starting-page = 1
journal = "International Journal of Interactive Multimedia and Artificial Intelligence"
special-issue-title = ""
special-issue = false
